#! /bin/bash

export WORKING_DIRECTORY=${HOME}/workspace
export ARC_DIR=${WORKING_DIRECTORY}/arc
export PICO_SDK_PATH=${ARC_DIR}/external/pico-sdk

#################################################################
#			               ALIASES
#################################################################

alias arc='cd ${ARC_DIR}'
alias tmux='tmux -f ${ARC_DIR}/config/tmux.conf'
alias nano='nano --rcfile=${ARC_DIR}/config/nanorc'

alias pf='pico_flash_swd'
alias pbf='pico_build; pico_flash_swd'
alias pcbf='pico_clean; pico_configure; pico_build; pico_flash_swd'

#################################################################
#			               SCRIPTS
#################################################################

# Loop through all .sh files in the folder
for file in ${ARC_DIR}/scripts/*.sh; do
    # Extract the file name without the extension
    file_name=$(basename "$file" .sh) 
    # Create an alias for each file
    alias "$file_name"="bash $file"
done
